"""Physics-based crack-length prediction without Lamb wave signals (Sec. 3.3).

Pre-processing (Sec. 3.3.1)
    The initial crack length corresponds to the zero cycle in fatigue crack
    initiation and propagation, so cycles are normalized: the crack-initiation
    cycle N_initial (first cycle with a nonzero — estimated or measured —
    crack length) is subtracted from all cycles, and zero-crack cycles are
    excluded.

Same loading condition — ensemble prognostics (Sec. 3.3.2, specimen T7)
    Each training specimen T1, T3, T4, T6 (T2/T5 dropped: too few points) is
    fitted with the sum of two exponentials (Eq. 6):
        a_N = A0*exp(A1*N) + B0*exp(B1*N)
    Prediction uses a simplified particle-filter-based weight update: at the
    current cycle each specimen model defines a Gaussian PDF centred on its
    own interpolated crack length; the weight of each specimen is the PDF
    value at the validation specimen's current (estimated or previously
    predicted) crack length; the weighted sum of the models' crack lengths at
    the next cycle is the prediction.

Different loading condition — Walker's equation model (Sec. 3.3.3, specimen T8)
    Walker's equation (Eq. 8) gives the per-cycle crack increment
        da_j = C0 * (Kmax * (1 - R)^gamma)_j^m,   Kmax = F * S * sqrt(pi*a)
    with F = 1. For the repeating variable-amplitude loading block (Table 2)
    the average growth per cycle over one repetition (Eq. 11) drives the
    numerical integration of Eq. 7. The four uncertain parameters
    d = {C0, gamma, m, sigma_FC} (sigma_FC = uncertainty of the crack length
    at the first nonzero-crack cycle) are estimated by evolutionary (genetic
    algorithm type) optimization of the weighted objective (Eq. 12):
        RMSE_WE(d) = (1/5) * sum_i i^2 * (y_WE_i(d) - y_i)^2
    whose i^2 weights emphasise the later cracks to prevent overestimation.
    Since the optimum depends on the initial design variables, 100 models are
    generated by Monte Carlo (random initializations) and averaged.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import curve_fit, differential_evolution

# ----------------------------------------------------------------------------
# Ensemble prognostics (same loading condition; used for specimen T7)
# ----------------------------------------------------------------------------


def double_exponential(n: np.ndarray, a0: float, a1: float, b0: float, b1: float) -> np.ndarray:
    """Eq. 6: a_N = A0*exp(A1*N) + B0*exp(B1*N)."""
    return a0 * np.exp(a1 * n) + b0 * np.exp(b1 * n)


@dataclass
class ExponentialModel:
    specimen: str
    params: np.ndarray

    def __call__(self, n) -> np.ndarray:
        return double_exponential(np.asarray(n, dtype=float), *self.params)


def fit_double_exponential(specimen: str, cycles: np.ndarray, cracks: np.ndarray) -> ExponentialModel:
    """Least-squares fit of Eq. 6 on normalized cycles (N=0 at initiation).

    The parameters are bounded to non-negative amplitudes and growth rates of
    at most 1.5e-3 per cycle: fatigue crack growth is monotonically
    increasing, and an unbounded fit can park a near-zero amplitude on a huge
    rate, which reproduces the data but explodes when the model is
    extrapolated a few thousand cycles ahead (the extrapolation is exactly
    how these models are used in the ensemble prognostics). The nonlinear
    least squares is restarted from 60 random initial guesses and the best
    solution kept, since single-start fits routinely stall in poor local
    minima for these small data sets."""
    cycles = cycles.astype(float)
    cracks = cracks.astype(float)
    rate_ub = 1.5e-3
    bounds = ([0.0, 0.0, 0.0, 0.0], [20.0, rate_ub, 20.0, rate_ub])
    rng = np.random.default_rng(0)
    best_params, best_sse = None, np.inf
    for _ in range(60):
        p0 = [rng.uniform(0, 3), rng.uniform(0, 3e-4), rng.uniform(0, 0.05), rng.uniform(2e-4, rate_ub)]
        try:
            params, _ = curve_fit(
                double_exponential, cycles, cracks, p0=p0, bounds=bounds, maxfev=20000
            )
        except RuntimeError:
            continue
        sse = float(np.sum((double_exponential(cycles, *params) - cracks) ** 2))
        if sse < best_sse - 1e-12:
            best_params, best_sse = params, sse
    return ExponentialModel(specimen, best_params)


class EnsemblePrognostics:
    """Simplified particle-filter-based ensemble prognostics (Figure 7).

    Each training-specimen exponential model is a 'particle'. At every
    prediction step:
      1. generate a Gaussian PDF per particle, centred on that model's crack
         length at the current cycle (sigma fixed; the paper does not report
         its value — Figure 7's illustrative PDFs suggest sigma ~= 1 mm, but
         sigma = 0.5 mm reproduces the paper's published T7 prediction
         trajectory more closely and is the default here);
      2. weight each particle by its PDF value at the current crack length of
         the validation specimen (estimated for the last cycle with signals,
         previously predicted afterwards) — the Gaussian's bounded maximum
         prevents the weights collapsing onto a single model;
      3. predict the next crack length as the weighted sum of the models'
         crack lengths at the next cycle.
    """

    def __init__(self, models: list[ExponentialModel], sigma_mm: float = 0.5) -> None:
        self.models = models
        self.sigma_mm = sigma_mm

    def weights(self, current_cycle: float, current_crack: float) -> np.ndarray:
        means = np.array([m(current_cycle) for m in self.models])
        pdf = np.exp(-0.5 * ((current_crack - means) / self.sigma_mm) ** 2) / (
            self.sigma_mm * np.sqrt(2 * np.pi)
        )
        return pdf / pdf.sum()

    def predict(
        self, start_cycle: float, start_crack: float, target_cycles: np.ndarray
    ) -> np.ndarray:
        """Sequentially predict the crack lengths at ``target_cycles``
        (normalized), starting from the last cycle with an estimate."""
        preds = []
        current_cycle, current_crack = float(start_cycle), float(start_crack)
        for next_cycle in np.asarray(target_cycles, dtype=float):
            w = self.weights(current_cycle, current_crack)
            crack_next = float(w @ np.array([m(next_cycle) for m in self.models]))
            preds.append(crack_next)
            current_cycle, current_crack = next_cycle, crack_next
        return np.asarray(preds)


# ----------------------------------------------------------------------------
# Walker's equation model (different loading condition; used for specimen T8)
# ----------------------------------------------------------------------------

# Variable-amplitude loading block (Table 2): (N_i cycles, S_max MPa, S_min MPa).
VARIABLE_LOADING_BLOCK = (
    (500, 91.0, 4.77),
    (500, 100.21, 4.77),
    (1, 100.21, 4.77),
)


class WalkerModel:
    """Walker's-equation crack growth under a repeating loading block.

    Crack lengths are handled in mm and stresses in MPa; the stress intensity
    factor uses the crack length in metres (K in MPa*sqrt(m)) with geometric
    parameter F = 1 (large plate).
    """

    def __init__(self, block=VARIABLE_LOADING_BLOCK) -> None:
        self.block = block
        self.n_block = sum(n for n, _, _ in block)

    def block_increment_mm(self, a_mm, c0, gamma, m):
        """Eq. 10: crack increase (mm) over one repetition of the block, with
        the crack length held at ``a_mm`` (vectorized over ``a_mm``)."""
        a_m = np.asarray(a_mm, dtype=float) * 1e-3
        da_m = 0.0
        for n_i, s_max, s_min in self.block:
            r = s_min / s_max
            k_max = s_max * np.sqrt(np.pi * a_m)
            da_m = da_m + n_i * c0 * (k_max * (1.0 - r) ** gamma) ** m
        return da_m * 1e3

    def integrate(self, a0_mm, target_cycles, c0, gamma, m):
        """Numerical integration of Eq. 7 using the average growth per cycle
        of the current block repetition (Eq. 11), evaluated at the (sorted)
        normalized ``target_cycles``. Vectorized over candidate parameter
        arrays ``a0_mm, c0, gamma, m``."""
        a = np.array(a0_mm, dtype=float, ndmin=1).copy()
        c0 = np.asarray(c0, dtype=float)
        gamma = np.asarray(gamma, dtype=float)
        m = np.asarray(m, dtype=float)
        targets = np.asarray(target_cycles, dtype=float)
        out = np.zeros((len(targets),) + a.shape)
        cycle = 0.0
        for it, target in enumerate(targets):
            while cycle < target:
                step = min(self.n_block, target - cycle)
                rate = self.block_increment_mm(a, c0, gamma, m) / self.n_block
                a = a + rate * step
                cycle += step
            out[it] = a
        return out


@dataclass
class WalkerFitResult:
    c0: float
    gamma: float
    m: float
    sigma_fc: float
    objective: float


class WalkerMonteCarlo:
    """GA-type optimization (Eq. 12) of the Walker model, repeated by Monte
    Carlo over random initializations; the averaged model predicts T8."""

    # Lower/upper bounds d_L <= d <= d_U for d = {C0, gamma, m, sigma_FC}.
    BOUNDS = [(1e-12, 1e-8), (0.0, 1.0), (2.0, 4.0), (-0.5, 0.5)]

    def __init__(self, fit_cycles, fit_cracks, n_models: int = 100, seed: int = 0) -> None:
        self.model = WalkerModel()
        self.fit_cycles = np.asarray(fit_cycles, dtype=float)
        self.fit_cracks = np.asarray(fit_cracks, dtype=float)
        self.n_models = n_models
        self.seed = seed
        self.fits: list[WalkerFitResult] = []

    def objective(self, params: np.ndarray) -> np.ndarray:
        """Eq. 12: weighted squared error with i^2 weights (vectorized: params
        has shape (4,) or (4, S))."""
        params = np.atleast_2d(params.T).T  # (4, S)
        c0, gamma, m, sigma_fc = params
        a0 = self.fit_cracks[0] + sigma_fc
        y = self.model.integrate(a0, self.fit_cycles, c0, gamma, m)  # (5, S)
        weights = (np.arange(1, len(self.fit_cycles) + 1) ** 2)[:, None]
        err = (y - self.fit_cracks[:, None]) ** 2
        return np.squeeze(np.mean(weights * err, axis=0))

    def fit(self) -> list[WalkerFitResult]:
        """Run the evolutionary optimization ``n_models`` times from random
        initial populations (Monte Carlo generation of Walker models)."""
        self.fits = []
        for k in range(self.n_models):
            res = differential_evolution(
                self.objective,
                bounds=self.BOUNDS,
                seed=self.seed + k,
                init="random",
                maxiter=200,
                tol=1e-10,
                vectorized=True,
                polish=False,
                updating="deferred",
            )
            self.fits.append(WalkerFitResult(*res.x, objective=float(res.fun)))
        return self.fits

    def predict(self, target_cycles) -> np.ndarray:
        """Average of the generated models' crack lengths at the (normalized)
        ``target_cycles``."""
        if not self.fits:
            self.fit()
        c0 = np.array([f.c0 for f in self.fits])
        gamma = np.array([f.gamma for f in self.fits])
        m = np.array([f.m for f in self.fits])
        sigma_fc = np.array([f.sigma_fc for f in self.fits])
        a0 = self.fit_cracks[0] + sigma_fc
        curves = self.model.integrate(a0, target_cycles, c0, gamma, m)  # (T, n_models)
        return curves.mean(axis=1)


def linear_regression_extrapolation(cycles, cracks, target_cycles) -> np.ndarray:
    """Simple linear regression of crack length vs. cycle, used to extend the
    three estimated T8 crack lengths to cycles 89237 and 92315 so that five
    points are available for building the Walker model (Sec. 3.3.3)."""
    coeffs = np.polyfit(np.asarray(cycles, float), np.asarray(cracks, float), 1)
    return np.polyval(coeffs, np.asarray(target_cycles, float))
