from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

RESULTS = Path(__file__).resolve().parent / "results"
TARGET = Path(__file__).resolve().parent / "priors.py"

TEMPLATE = '''# Generated by `python -m physics_calibration.make_priors`; do not edit by hand.
# Units: da/dN in m/cycle, dK in MPa*sqrt(m), crack length in m, stress in MPa.
from __future__ import annotations

# (n_cycles, Smax MPa, Smin MPa)
CONSTANT_LOAD_BLOCK = {constant_block!r}
VARIABLE_LOAD_BLOCK = {variable_block!r}

STRESS_RATIO_RANGE = ({r_min!r}, {r_max!r})

# Minimax exponent for blind prognosis, scored on the training specimens only.
RECOMMENDED_EXPONENT = {recommended_m!r}
RECOMMENDED_EXPONENT_PRIOR_SD = {recommended_m_sd!r}
# Re-identified at RECOMMENDED_EXPONENT: C and m move together along the
# log-log ridge, so a coefficient taken at another exponent is not valid.
RECOMMENDED_LOG10_C = {rec_logc_mean!r}
RECOMMENDED_LOG10_C_STD = {rec_logc_std!r}
RECOMMENDED_C = {rec_c!r}
RECOMMENDED_LOG10_C_BY_SPECIMEN = {rec_logc_by_spec!r}

PARIS_EXPONENT = {paris_m!r}
PARIS_LOG10_C = {paris_logc_mean!r}
PARIS_LOG10_C_STD = {paris_logc_std!r}
PARIS_C = {paris_c!r}
PARIS_LOG10_C_BY_SPECIMEN = {paris_logc_by_spec!r}

LOGLOG_EXPONENT = {loglog_m!r}
LOGLOG_EXPONENT_CI95 = {loglog_m_ci!r}
LOGLOG_C = {loglog_c!r}
LOGLOG_R2 = {loglog_r2!r}
LOGLOG_RESIDUAL_SD_DEX = {loglog_sd!r}

LOG10_C_BOUNDS = {log_c_bounds!r}
EXPONENT_BOUNDS = {m_bounds!r}

# With two anchors, all the signals of T7/T8 provide, every law diverges on T8.
MIN_ANCHOR_POINTS = 3

WALKER_GAMMA = {walker_gamma!r}
WALKER_GAMMA_IDENTIFIABLE = False

HOLE_KT = {hole_kt!r}
HOLE_DECAY_MM = {hole_lambda!r}
HOLE_EXPONENT = {hole_m!r}
HOLE_LOG10_C = {hole_logc!r}


# Schijve, Fatigue of Structures and Materials, Eq. 9.10.
def elber_schijve_closure(r):
    return 0.55 + 0.35 * r + 0.1 * r ** 2


LITERATURE_REFERENCE = {literature!r}
'''


def _round(x, n=4):
    return float(np.round(float(x), n))


def main() -> None:
    best = json.loads((RESULTS / "stage_b_pooled_best.json").read_text())
    loglog = json.loads((RESULTS / "stage_e_loglog.json").read_text())
    profile = json.loads((RESULTS / "stage_c_profile_m.json").read_text())["profile"]
    sweep = pd.read_csv(RESULTS / "stage_g_exponent_sweep.csv")

    # Scored on the training specimens only: selecting on T7/T8 would be leakage.
    pivot = sweep.pivot(index="m", columns="n_anchor", values="penalty_train")
    worst = pivot.max(axis=1)
    admissible = worst[worst.index >= 2.0]
    recommended_m = float(admissible.idxmin())
    # Half the span of exponents within 50 % of the minimax optimum.
    tolerated = admissible[admissible <= 1.5 * admissible.min()].index
    recommended_sd = float(max(0.2, (tolerated.max() - tolerated.min()) / 4.0))

    from .data import CALIBRATION_SPECIMENS, load_curve
    from .models import LAWS
    from .pooled import fit_coefficient_only

    rec_logc = {
        spec: fit_coefficient_only(
            LAWS["paris"], np.array([recommended_m]), load_curve(spec)
        )[0]
        for spec in CALIBRATION_SPECIMENS
    }
    rec_values = np.array(list(rec_logc.values()))

    paris = best["paris"]
    walker = best["walker"]
    hole = best.get("paris_hole", paris)

    best_obj = min(p["objective"] for p in profile)
    inside = [p["value"] for p in profile if p["objective"] <= 1.05 * best_obj]

    t1, t8 = load_curve("T1"), load_curve("T8")
    r_values = [seg[2] / seg[1] for c in (t1, t8) for seg in c.load_block]

    p = loglog["pooled"]
    text = TEMPLATE.format(
        today=date.today().isoformat(),
        m_lo=min(inside), m_hi=max(inside),
        decades=float(np.log10(p["delta_k_max"] / p["delta_k_min"])),
        constant_block=[[float(v) for v in seg] for seg in t1.load_block],
        variable_block=[[float(v) for v in seg] for seg in t8.load_block],
        r_min=_round(min(r_values), 5), r_max=_round(max(r_values), 5),
        recommended_m=recommended_m, recommended_m_sd=_round(recommended_sd, 2),
        rec_logc_mean=_round(rec_values.mean()),
        rec_logc_std=_round(rec_values.std(ddof=1)),
        rec_c=float(f"{10 ** rec_values.mean():.4g}"),
        rec_logc_by_spec={k: _round(v) for k, v in rec_logc.items()},
        c_factor=float(10 ** paris["log10_coefficient_std"]),
        pen_3=float(sweep.loc[(sweep.n_anchor == 3) & (np.isclose(sweep.m, recommended_m)),
                              "penalty_train"].iloc[0]),
        pen_4=float(sweep.loc[(sweep.n_anchor == 4) & (np.isclose(sweep.m, recommended_m)),
                              "penalty_train"].iloc[0]),
        paris_m=_round(paris["shared"]["m"]),
        paris_logc_mean=_round(paris["log10_coefficient_mean"], 4),
        paris_logc_std=_round(paris["log10_coefficient_std"], 4),
        paris_c=float(f"{10 ** paris['log10_coefficient_mean']:.4g}"),
        paris_logc_by_spec={k: _round(v) for k, v in paris["log10_coefficients"].items()},
        paris_rmse=paris["objective_mean_rmse_mm"],
        walker_rmse=walker["objective_mean_rmse_mm"],
        walker_gamma=_round(walker["shared"]["gamma"]),
        hole_rmse=hole["objective_mean_rmse_mm"],
        hole_kt=_round(hole["shared"].get("Kt", float("nan"))),
        hole_lambda=_round(hole["shared"].get("lambda_h", float("nan"))),
        hole_m=_round(hole["shared"]["m"]),
        hole_logc=_round(hole["log10_coefficient_mean"]),
        loglog_m=_round(p["m"], 3), loglog_m_ci=_round(p["m_ci95"], 3),
        loglog_c=float(f"{p['C']:.4g}"), loglog_r2=_round(p["r2"], 3),
        loglog_sd=_round(p["residual_sd_dex"], 3),
        log_c_bounds=(-13.0, -6.0),
        m_bounds=(2.0, 4.0),
        literature={
            "Dourado & Viana (2019), Al 2024-T3 coupons (Menan & Henaff 2010), air": {
                "C": 5.008e-10, "m": 3.859,
                "note": "units not recoverable from the paper; do not use as-is",
            },
            "Metals 13(8):1134 (2023), AA 2024-T4, modified CT, R = -1": {
                "C": 5.75e-8, "m": 3.09,
            },
            "Rao et al. (2021) after Li, Wang & Gong (2012), generic metals": {
                "C_range": (1e-13, 1e-11), "m_range": (2.0, 4.0),
            },
        },
    )
    TARGET.write_text(text)
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
