# Generated by `python -m physics_calibration.make_priors`; do not edit by hand.
# Units: da/dN in m/cycle, dK in MPa*sqrt(m), crack length in m, stress in MPa.
from __future__ import annotations

# (n_cycles, Smax MPa, Smin MPa)
CONSTANT_LOAD_BLOCK = [[1.0, 100.21, 4.77]]
VARIABLE_LOAD_BLOCK = [[500.0, 90.0, 4.77], [500.0, 100.21, 4.77]]

STRESS_RATIO_RANGE = (0.0476, 0.053)

# Minimax exponent for blind prognosis, scored on the training specimens only.
RECOMMENDED_EXPONENT = 2.25
RECOMMENDED_EXPONENT_PRIOR_SD = 0.2
# Re-identified at RECOMMENDED_EXPONENT: C and m move together along the
# log-log ridge, so a coefficient taken at another exponent is not valid.
RECOMMENDED_LOG10_C = -8.6675
RECOMMENDED_LOG10_C_STD = 0.0932
RECOMMENDED_C = 2.15e-09
RECOMMENDED_LOG10_C_BY_SPECIMEN = {'T1': -8.72, 'T3': -8.69, 'T4': -8.73, 'T6': -8.53}

PARIS_EXPONENT = 2.0632
PARIS_LOG10_C = -8.4872
PARIS_LOG10_C_STD = 0.0849
PARIS_C = 3.257e-09
PARIS_LOG10_C_BY_SPECIMEN = {'T1': -8.5346, 'T3': -8.4971, 'T4': -8.5525, 'T6': -8.3647}

LOGLOG_EXPONENT = 2.566
LOGLOG_EXPONENT_CI95 = 1.302
LOGLOG_C = 8.729e-10
LOGLOG_R2 = 0.332
LOGLOG_RESIDUAL_SD_DEX = 0.298

LOG10_C_BOUNDS = (-13.0, -6.0)
EXPONENT_BOUNDS = (2.0, 4.0)

# With two anchors, all the signals of T7/T8 provide, every law diverges on T8.
MIN_ANCHOR_POINTS = 3

WALKER_GAMMA = 0.4004
WALKER_GAMMA_IDENTIFIABLE = False

HOLE_KT = 8.0
HOLE_DECAY_MM = 0.4688
HOLE_EXPONENT = 4.4846
HOLE_LOG10_C = -10.9441


# Schijve, Fatigue of Structures and Materials, Eq. 9.10.
def elber_schijve_closure(r):
    return 0.55 + 0.35 * r + 0.1 * r ** 2


LITERATURE_REFERENCE = {'Dourado & Viana (2019), Al 2024-T3 coupons (Menan & Henaff 2010), air': {'C': 5.008e-10, 'm': 3.859, 'note': 'units not recoverable from the paper; do not use as-is'}, 'Metals 13(8):1134 (2023), AA 2024-T4, modified CT, R = -1': {'C': 5.75e-08, 'm': 3.09}, 'Rao et al. (2021) after Li, Wang & Gong (2012), generic metals': {'C_range': (1e-13, 1e-11), 'm_range': (2.0, 4.0)}}
